travis:
  secure:
    BINSTAR_TOKEN: v+SlwxUuRxVcXc3q5RPFqlfaXSmZvbXxs4jjVQn667r4IB6TOMHed4Tktp874PDkUn2FsVNDQwu6et174nknpjpEhXbfGbogBtIClDoltR4+G2ywqU6Tp0myrVd9cz2eloMinkHyObXH8BoT8tpthtcq1lqSbAUBcvSzB07CE+QxS96UyN4TzP6HRdQDTUdP8aaYSQtubWkZxc2X19n1FespJ3o8WR0k2TKZWn4ph6LwSlqNeFA4jk7LNjysRNeqak97eJS82IucIOs2i4TS7AqWqU5ZagO+UifGFmKwVWRsBMB69ThnTtTSF1PHvOg4H+KzbzkErJJKlwo8uPE7/vTYk4ibyT/58vII760AdqBWVBQK9wOdKt39O/6e10W+w1dgW1gc3urLeP0lRHDVY4ObavyJvm0rb2B3CzRtADmBRe0bg/Nl66fd0mGrCS8Oim++vRXp/K9JrLkMgYRXR/FkJu9CMpyo6cFTXqAglCkzryuJT7VV2w8u0Mtiq2+q3RZ4mkNAE1tXXM7mTdzhA21+4hNmX2HmJQQRwTgqG/UptPyEgNTqGKh+F77lEQE+dAEKCPTFMix2YAQ38/MJ3gjwwy0sVaH/sTS11ai3nK+FVN61v4zlGfO/9qTwTNrBjjaVGGn1SOJWMSU7gL3sWBcCx7jv+QAPtCjFaVQYOUs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
