travis:
  secure:
    BINSTAR_TOKEN: WZTUYc+JsUdHzvbzlIIP8PpFt1HIL4LRDqIH8DjYkPRqWBDSe36oJX37xcSzE3bUcYWNV4205D4Q+sB24kY62xOqAtwstQCaYfXQW+eXAi/71Cg3fEWslXAC6HcQS9ltNtm6xXeSvfwpRyEMowi2K1ngQO57D+q6D3L1/Nkr1v1Y8ZNbHcPmDFJ9jQVIHl5wXFzcmW237SOv3+OZec8gSNbxiI9fimC1udZEWJ3XH1rfsds+P2xx8MIOuJL1OcOFEoZcYo/ZklzqR0VkV1gB1vPrunMbpzpkMg2anU++n3mOywtwqYwpoEIwyd51qS4nJZHAcSn/rRSuNOYEbOJwnI6NFq6MNULxjBjU6qkVlVzuPDWMQZp8QwOecq5jsny7fvvjaSzMQyvtuYu7ct0ff3DfbZImOteNNTeaEhH0vlGwts6RVQqofZkNNicwKl0ApkloSB+276AOoILrCtjxSYgCJw8G7knlFczL85y/+cys7w8CgV9DPqbo5fgLH98kYFMWwuDAMLosraakxdaa737Nkk6qgLg0tIzIR9qt9ea2Y9pqFbjFx4aZdhSjae/SN4XT5OUh2K6ehx7AaLzFKAyPzJqjtVU7ZLNU2vDPbnaEVXt5XFN+cXvp7v6RAftfqBiego0PKgn/P4RcYr4o8q9xMFFmsXiVa5aGJVifzXQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
